version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "notes:none"
      - "type:ci"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "web/"
    schedule:
      interval: "weekly"
    labels:
      - "notes:none"
      - "scope:web"
      - "type:chore"
    groups:
      webui:
        patterns:
          - "*"
