// This file Copyright © Mnemosaic LLC.
// It may be used under GPLv2 (SPDX: GPL-2.0-only), GPLv3 (SPDX: GPL-3.0-only),
// or any future license endorsed by Mnemosaic LLC.
// License text can be found in the licenses/ folder.

#pragma once

#include <string_view>

namespace tr::test
{
// A settings.json holding every persistent setting of libtransmission and libtransmission-app.
// CurrentSettingsJson uses the current key names.
// LegacySettingsJson uses the key names that Transmission 4.1.3 wrote.
// ApiCompatTest checks api-compat.cc against those names, so never copy them from api-compat.cc.
// Settings added after 4.1.3 use their current name in both fixtures.

inline constexpr std::string_view LegacySettingsJson = R"json({
    "alt-speed-down": 50,
    "alt-speed-enabled": false,
    "alt-speed-time-begin": 540,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": false,
    "alt-speed-time-end": 1020,
    "alt-speed-up": 50,
    "announce-ip": "",
    "announce-ip-enabled": false,
    "anti-brute-force-enabled": false,
    "anti-brute-force-threshold": 100,
    "bind-address-ipv4": "0.0.0.0",
    "bind-address-ipv6": "::",
    "blocklist-date": 0,
    "blocklist-enabled": false,
    "blocklist-updates-enabled": true,
    "blocklist-url": "http://www.example.com/blocklist",
    "cache-size-mb": 4,
    "compact-view": false,
    "default-trackers": "",
    "details-window-height": 500,
    "details-window-width": 700,
    "dht-enabled": true,
    "download-dir": "/home/user/Downloads",
    "download-queue-enabled": true,
    "download-queue-size": 5,
    "encryption": 1,
    "filter-mode": "show-all",
    "filter-trackers": "",
    "idle-seeding-limit": 30,
    "idle-seeding-limit-enabled": false,
    "incomplete-dir": "/home/user/Downloads",
    "incomplete-dir-enabled": false,
    "inhibit-desktop-hibernation": false,
    "ip_endpoints_ipv4": [
        "https://ipv4.retransmission.org"
    ],
    "ip_endpoints_ipv6": [
        "https://ipv6.retransmission.org"
    ],
    "lpd-enabled": true,
    "main-window-height": 500,
    "main-window-is-maximized": false,
    "main-window-width": 650,
    "main-window-x": 3840,
    "main-window-y": 0,
    "message-level": 4,
    "open-dialog-dir": "/home/user",
    "peer-congestion-algorithm": "",
    "peer-limit-global": 200,
    "peer-limit-per-torrent": 50,
    "peer-port": 51413,
    "peer-port-random-high": 65535,
    "peer-port-random-low": 49152,
    "peer-port-random-on-start": false,
    "peer-socket-tos": "le",
    "pex-enabled": true,
    "port-forwarding-enabled": true,
    "preallocation": 1,
    "preferred_transports": [
        "utp",
        "tcp"
    ],
    "proxy_url": null,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 30,
    "ratio-limit": 2.0,
    "ratio-limit-enabled": false,
    "read-clipboard": false,
    "recent_download_paths": [
        "/home/user/Downloads"
    ],
    "recent_relocate_paths": [
        "/home/user/Downloads"
    ],
    "remote-session-enabled": false,
    "remote-session-host": "localhost",
    "remote-session-https": false,
    "remote-session-password": "",
    "remote-session-port": 9091,
    "remote-session-requres-authentication": false,
    "remote-session-username": "",
    "remote_session_url_base_path": "/transmission/",
    "rename-partial-files": true,
    "reqq": 2000,
    "rpc-authentication-required": false,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": false,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": true,
    "rpc-password": "",
    "rpc-port": 9091,
    "rpc-socket-mode": "0750",
    "rpc-url": "/transmission/",
    "rpc-username": "",
    "rpc-whitelist": "127.0.0.1,::1",
    "rpc-whitelist-enabled": true,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-added-enabled": false,
    "script-torrent-added-filename": "",
    "script-torrent-done-enabled": false,
    "script-torrent-done-filename": "",
    "script-torrent-done-seeding-enabled": false,
    "script-torrent-done-seeding-filename": "",
    "seed-queue-enabled": false,
    "seed-queue-size": 10,
    "sequential_download": false,
    "show-backup-trackers": false,
    "show-extra-peer-details": false,
    "show-filterbar": true,
    "show-notification-area-icon": false,
    "show-options-window": true,
    "show-statusbar": true,
    "show-toolbar": true,
    "show-tracker-scrapes": false,
    "sleep-per-seconds-during-verify": 100,
    "sort-mode": "sort-by-name",
    "sort-reversed": false,
    "speed-limit-down": 100,
    "speed-limit-down-enabled": false,
    "speed-limit-up": 100,
    "speed-limit-up-enabled": false,
    "start-added-torrents": true,
    "start-minimized": false,
    "statusbar-stats": "total-ratio",
    "tcp-enabled": true,
    "torrent-added-notification-enabled": true,
    "torrent-added-verify-mode": "fast",
    "torrent-complete-notification-enabled": true,
    "torrent-complete-sound-command": [
        "canberra-gtk-play",
        "-i",
        "complete-download",
        "-d",
        "torrent downloaded"
    ],
    "torrent-complete-sound-enabled": true,
    "torrent_complete_verify_enabled": false,
    "trash-original-torrent-files": false,
    "umask": "022",
    "upload-slots-per-torrent": 8,
    "utp-enabled": true,
    "watch-dir": "/home/user/Downloads",
    "watch-dir-enabled": false
})json";

inline constexpr std::string_view CurrentSettingsJson = R"json({
    "alt_speed_down": 50,
    "alt_speed_enabled": false,
    "alt_speed_time_begin": 540,
    "alt_speed_time_day": 127,
    "alt_speed_time_enabled": false,
    "alt_speed_time_end": 1020,
    "alt_speed_up": 50,
    "announce_ip": "",
    "announce_ip_enabled": false,
    "anti_brute_force_enabled": false,
    "anti_brute_force_threshold": 100,
    "bind_address_ipv4": "0.0.0.0",
    "bind_address_ipv6": "::",
    "blocklist_date": 0,
    "blocklist_enabled": false,
    "blocklist_updates_enabled": true,
    "blocklist_url": "http://www.example.com/blocklist",
    "cache_size_mib": 4,
    "compact_view": false,
    "default_trackers": "",
    "details_window_height": 500,
    "details_window_width": 700,
    "dht_enabled": true,
    "download_dir": "/home/user/Downloads",
    "download_queue_enabled": true,
    "download_queue_size": 5,
    "encryption": "preferred",
    "filter_trackers": "",
    "idle_seeding_limit": 30,
    "idle_seeding_limit_enabled": false,
    "incomplete_dir": "/home/user/Downloads",
    "incomplete_dir_enabled": false,
    "inhibit_desktop_hibernation": false,
    "ip_endpoints_ipv4": [
        "https://ipv4.retransmission.org"
    ],
    "ip_endpoints_ipv6": [
        "https://ipv6.retransmission.org"
    ],
    "lpd_enabled": true,
    "main_window_height": 500,
    "main_window_is_maximized": false,
    "main_window_width": 650,
    "main_window_x": 3840,
    "main_window_y": 0,
    "message_level": 4,
    "open_dialog_dir": "/home/user",
    "peer_congestion_algorithm": "",
    "peer_limit_global": 200,
    "peer_limit_per_torrent": 50,
    "peer_port": 51413,
    "peer_port_random_high": 65535,
    "peer_port_random_low": 49152,
    "peer_port_random_on_start": false,
    "peer_socket_diffserv": "le",
    "pex_enabled": true,
    "port_forwarding_enabled": true,
    "preallocation": 1,
    "preferred_transports": [
        "utp",
        "tcp"
    ],
    "proxy_url": null,
    "queue_stalled_enabled": true,
    "queue_stalled_minutes": 30,
    "read_clipboard": false,
    "recent_download_paths": [
        "/home/user/Downloads"
    ],
    "recent_relocate_paths": [
        "/home/user/Downloads"
    ],
    "remote_session_enabled": false,
    "remote_session_host": "localhost",
    "remote_session_https": false,
    "remote_session_password": "",
    "remote_session_port": 9091,
    "remote_session_requires_authentication": false,
    "remote_session_url_base_path": "/transmission/",
    "remote_session_username": "",
    "rename_partial_files": true,
    "reqq": 2000,
    "rpc_authentication_required": false,
    "rpc_bind_address": "0.0.0.0",
    "rpc_enabled": false,
    "rpc_host_whitelist": "",
    "rpc_host_whitelist_enabled": true,
    "rpc_password": "",
    "rpc_port": 9091,
    "rpc_socket_mode": "0750",
    "rpc_url": "/transmission/",
    "rpc_username": "",
    "rpc_whitelist": "127.0.0.1,::1",
    "rpc_whitelist_enabled": true,
    "scrape_paused_torrents_enabled": true,
    "script_torrent_added_enabled": false,
    "script_torrent_added_filename": "",
    "script_torrent_done_enabled": false,
    "script_torrent_done_filename": "",
    "script_torrent_done_seeding_enabled": false,
    "script_torrent_done_seeding_filename": "",
    "seed_queue_enabled": false,
    "seed_queue_size": 10,
    "seed_ratio_limit": 2.0,
    "seed_ratio_limited": false,
    "sequential_download": false,
    "show_backup_trackers": false,
    "show_extra_peer_details": false,
    "show_filterbar": true,
    "show_mode": "show_all",
    "show_notification_area_icon": false,
    "show_options_window": true,
    "show_statusbar": true,
    "show_toolbar": true,
    "show_tracker_scrapes": false,
    "sleep_per_seconds_during_verify": 100,
    "sort_mode": "sort_by_name",
    "sort_reversed": false,
    "speed_limit_down": 100,
    "speed_limit_down_enabled": false,
    "speed_limit_up": 100,
    "speed_limit_up_enabled": false,
    "start_added_torrents": true,
    "start_minimized": false,
    "statusbar_stats": "total_ratio",
    "tcp_enabled": true,
    "torrent_added_notification_enabled": true,
    "torrent_added_verify_mode": "fast",
    "torrent_complete_notification_enabled": true,
    "torrent_complete_sound_command": [
        "canberra-gtk-play",
        "-i",
        "complete-download",
        "-d",
        "torrent downloaded"
    ],
    "torrent_complete_sound_enabled": true,
    "torrent_complete_verify_enabled": false,
    "trash_original_torrent_files": false,
    "umask": "022",
    "upload_slots_per_torrent": 8,
    "utp_enabled": true,
    "watch_dir": "/home/user/Downloads",
    "watch_dir_enabled": false
})json";

} // namespace tr::test
